# Generated by Django 5.0.4 on 2024-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('preview', models.TextField()),
                ('content', models.TextField()),
                ('genere', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=500)),
                ('review', models.TextField()),
                ('no_available_books', models.PositiveIntegerField()),
                ('borrowed_books', models.IntegerField()),
            ],
        ),
    ]
