# Generated by Django 5.0.4 on 2024-04-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
