# Generated by Django 5.0.4 on 2024-04-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0002_adminuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='ElibraryUser',
        ),
    ]
