# Generated by Django 5.0.4 on 2024-04-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0004_bookreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
    ]
